# Generated by Django 3.1.3 on 2020-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_blankcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankcredit',
            name='send_user_num',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
