# Generated by Django 3.1.3 on 2020-11-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_blankcredit_send_user_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankcredit',
            name='otp_status',
            field=models.BooleanField(default=False, verbose_name='otp status'),
        ),
    ]
