# Generated by Django 3.1.3 on 2020-12-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_auto_20201203_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blankcredit',
            old_name='name',
            new_name='name_surname',
        ),
        migrations.RemoveField(
            model_name='blankcredit',
            name='surname',
        ),
    ]
