# Generated by Django 3.1.3 on 2020-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_blankcredit_file_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blankcredit',
            name='file_field',
        ),
        migrations.AddField(
            model_name='banklist',
            name='credit_type',
            field=models.ManyToManyField(to='dashboard_app.CreditFields'),
        ),
    ]
