# Generated by Django 3.1.3 on 2020-12-11 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0009_auto_20201211_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditTypeInterest',
        ),
        migrations.AddField(
            model_name='banklist',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard_app.creditfields'),
        ),
        migrations.AddField(
            model_name='banklist',
            name='interest',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
