# Generated by Django 3.1.3 on 2020-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_auto_20201211_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankcredit',
            name='send_user_num',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
