# Generated by Django 3.1.3 on 2020-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0012_auto_20201216_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankcredit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
