# Generated by Django 3.1.3 on 2020-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_auto_20201217_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankcredit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
