# Generated by Django 3.1.3 on 2020-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankfiles',
            old_name='files',
            new_name='file',
        ),
    ]
