# Generated by Django 3.1.3 on 2020-12-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20201215_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankfiles',
            old_name='file',
            new_name='files',
        ),
    ]
