# Generated by Django 3.1.3 on 2020-12-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_auto_20201215_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankFiles',
        ),
    ]
