# Generated by Django 3.1.3 on 2020-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_bankfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankfiles',
            name='files',
            field=models.FileField(blank=True, default='None', null=True, upload_to='Bank_Inovice'),
        ),
    ]
