# Generated by Django 3.1.3 on 2020-11-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditFields',
        ),
    ]
