# Generated by Django 3.1.3 on 2020-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_delete_creditfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='MY_USER_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
