# Generated by Django 3.1.3 on 2020-12-14 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_myuser_my_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cash_back',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
