# Generated by Django 3.1.3 on 2020-12-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_myuser_cash_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='MY_USER_ID',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
