# Generated by Django 3.1.3 on 2020-12-17 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20201216_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='HavayiCashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_back', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
    ]
